#✦------------------------------------------------------✦
#|                      Main Config                     |
#✦------------------------------------------------------✦
#RealScoreboard created by JoseGamerPT and maintained by Neziw
#
#Useful links:
#SpigotMC - https://www.spigotmc.org/resources/realscoreboard-1-13-to-1-19-2.22928/
#Discord Server - https://discord.gg/t7gfnYZKy8
#bStats - https://bstats.org/plugin/bukkit/RealScoreboard/10080
#HEX Color Formats: https://github.com/Iridium-Development/IridiumColorAPI
#API for Developers: https://github.com/JoseGamerPT/RealScoreboard/blob/master/api.md
Debug: false
Config:
  ItemAdder-Support: false
  mcMMO-Support: false
  Check-for-Updates: true
  Prefix: '&bReal&9Scoreboard &7| &r'
  Reloaded: '&fThe config has been &areloaded&f.'
  Use-Placeholders-In-Scoreboard-Titles: false
  RealScoreboard-Disabled-By-Default: false
  Hours:
    Formatting: 'HH:mm:ss'
    Offset: 0
  Messages:
    Scoreboard-Toggle:
      'ON': '&fScoreboard turned &aON&f.'
      'OFF': '&fScoreboard turned &cOFF&f.'
  Animations:
    Title-Delay: 20
    Loop-Delay: 20
  Scoreboard-Refresh: 10
  Disabled-Worlds:
    - testWorld
    - ExampleWorld2
  Bypass-Worlds:
    - skywarsLobby
  Scoreboard:
    world:
      special:
        Switch-Timer: 50
        Boards:
          Board1:
            Title:
              - '&bRealScoreBoard'
              - '&6> &9RealScoreBoard &6<'
              - '&a>&6> &bRealScoreBoard &6<&a<'
              - '&6> &9RealScoreBoard &6<'
            Lines:
              - '%blank%'
              - ' &aSpecial Permission Board'
              - '%blank%'
      default:
        Switch-Timer: 35
        Boards:
          Board1:
            Title:
              - '&bRealScoreBoard'
              - '&6> &9RealScoreBoard &6<'
              - '&a>&6> &bRealScoreBoard &6<&a<'
              - '&6> &9RealScoreBoard &6<'
            Lines:
              - '%blank%'
              - ' &7Name: &f%playername% &8| &f%ping%'
              - ' &f%day% &8| &f%time%'
              - ' &7Money: &f%money% &8| &7XP: &f%xp%'
              - ' &7Location:'
              - ' &fX %x% Y %y% Z %z%'
              - '%blank%'
              - '  &fThis is Board &e#1'
              - '%blank%'
              - ' &7RAM: &f%ram%'
              - ' &7Online: &f%online%&8/&f%maxplayers%'
              - '%blank%'
          Board2:
            Title:
              - '&bStatistics &aBoard'
              - '&aStatistics &bBoard'
            Lines:
              - '%blank%'
              - ' &7Stats'
              - '  &fKills: %kills% &7| &fKD: %kd%'
              - '  Mob Kills: %mobkills%'
              - '  Deaths: %deaths%'
              - '  Jumps: %jumps%'
              - '%blank%'
              - ' &fThis is Board &e#2'
              - '%blank%'
Version: 14